ZScript RPG system review
DRRP-Team/DRRP pull request #11
Opened 2019-03-25 21:54 UTC by MorthimerMcMare

Итак, нужна проверка моей RPG-системы.

2019-03-25 21:57 UTC, PROPHESSOR commented
![screenshot](https://media.discordapp.net/attachments/505122055935623199/559856752091463680/unknown.png)
Уже дошел сюда, а повышения уровня всё не было... Обычно, оно происходит перед дверью 1234

2019-03-25 21:57 UTC, PROPHESSOR commented
![screenshot](https://media.discordapp.net/attachments/505122055935623199/559857008786931712/unknown.png)
У меня уже второй уровень

2019-03-25 21:58 UTC, MorthimerMcMare commented
Понимаешь, у тебя ящики и огонь тоже учитывалить, а я их пока отключил.

2019-03-25 21:58 UTC, PROPHESSOR commented
Не надо их отключать

2019-03-25 21:59 UTC, PROPHESSOR commented
![image](https://user-images.githubusercontent.com/19251320/54956907-eab62500-4f59-11e9-8e1d-e7516873118e.png)
Ничего себе! Нужно 54 монстра убить, чтобы получить 3 уровень?!

2019-03-25 21:59 UTC, MorthimerMcMare commented
Ну да. Пока так.

2019-03-25 22:04 UTC, PROPHESSOR commented
На третьем уровне все монстры первого уровня умирают с одного-двух выстрелов пистолета...

2019-03-25 22:08 UTC, PROPHESSOR commented
Собаки не берут урон на себя

2019-03-25 22:19 UTC, PROPHESSOR commented
Защита не учитывается при получении урона
![image](https://user-images.githubusercontent.com/19251320/54957931-d293d500-4f5c-11e9-9098-f0feb9489529.png)

2019-03-25 22:20 UTC, PROPHESSOR commented
Блокирование урона топором не работает

2019-03-25 22:36 UTC, PROPHESSOR commented
Обобщу:
- Требуется слишком много опыта для перехода на следующий уровень
- В опыт не учитывается ломание предметов/тушение огня/открытие заклинивших дверей/открывание сундуков/взрывание бочек
- В окошке отображается предыдущий уровень, а не тот, на который игрок только что перешел
- Слишком читерский урон при прокачке силы, хотя бы, до 8
- Собаки не берут урон на себя
- Топор не блокирует часть урона, так же, нет звука блокировки

2019-03-25 22:38 UTC, PROPHESSOR requested changes
Ах да, я забыл запустить Review)

2019-03-25 22:38 UTC, MorthimerMcMare commented
Исправил всё, что не относится к балансу (фактические ошибки).

2019-03-25 22:43 UTC, MorthimerMcMare commented
Остальное нужно подбирать долгим путём. Баланс относится к RPG-системе, но не к фундаменту оной, и считать его ошибки фатальными (запрещающими делать "Merge pull request") как минимум странно, как максимум -- глупо.

2019-03-25 22:49 UTC, PROPHESSOR commented
```Исправил всё, что не относится к балансу (фактические ошибки).```
Увы, нет. Я отметил выполненные пункты (см. описание PR'а)

```Остальное нужно подбирать долгим путём. Баланс относится к RPG-системе, но не к фундаменту оной, и считать его ошибки фатальными (запрещающими делать "Merge pull request") как минимум странно, как максимум -- глупо.```
Не соглашусь. В ветке master должна быть более-менее стабильная версия.
Т.е. нужно прикинуть баланс, чтобы он был в разумных пределах, а не оставлять надежду под конец игры получить 10 уровень.

2019-03-25 23:01 UTC, MorthimerMcMare commented
>>Не соглашусь. В ветке master должна быть более-менее стабильная версия.
>>Т.е. нужно прикинуть баланс, чтобы он был в разумных пределах, а не оставлять надежду под конец игры получить 10 уровень.
Ну... Опять же, не соглашусь. В твоей версии баланса также не было, однако этот ACS-код был спокойно отправлен в `master` (все значения урона, защиты и так далее брал с твоего кода; изменил только количество опыта, требуемое для перехода на следующий уровень). Возможно, также у тебя баланс казался более верным из-за [бага при смене карты](https://trello.com/c/mG7WE3eO/), но это засчитывать за плюс будет верхом "Это не баг, это фича" (напомню, что фактический уровень и значения атрибутов игрока у тебя посмотреть было нельзя, в StatInfo они не выводились).

>> Увы, нет. Я отметил выполненные пункты (см. описание PR'а)
Всё, что не относится к балансу -- выполнил. По остальному поставлен вопрос насчёт твоего ACS-баланса (см. первый пункт).

2019-03-25 23:26 UTC, PROPHESSOR commented
Выделил полужирным пункт, без которого не пущу =D

2019-03-26 07:21 UTC, MorthimerMcMare commented
Уговорил. Сделаю небольшой баланс. Также добавлю разное количество опыта за каждого из монстров (дай примерную таблицу).

2019-03-26 09:55 UTC, PROPHESSOR commented
> дай примерную таблицу

Я знаю не больше твоего... В оригинале такого не было, соответственно, необходимо придумать самим

2019-03-26 16:47 UTC, PROPHESSOR approved these changes

2019-03-26 16:48 UTC, PROPHESSOR commented
Принято

2019-03-26 16:52 UTC, merged