Исправление русского перевода от Russian Doom Community
DRRP-Team/DRRP pull request #9
Opened 2019-02-20 18:29 UTC by PROPHESSOR

В процессе

2019-03-03 07:39 UTC, PROPHESSOR commented
![image](https://user-images.githubusercontent.com/19251320/53692417-282ef480-3d98-11e9-9c1e-aabc8e6ac2f7.png)
Лучше так: ```Всему личному составу нужно собраться в Переходе!```

2019-03-03 07:44 UTC, PROPHESSOR commented
![image](https://user-images.githubusercontent.com/19251320/53692454-de92d980-3d98-11e9-9e63-166c6983c774.png)

2019-03-03 07:45 UTC, PROPHESSOR commented
Неверный контекст. У него, как раз, есть автокарта, т.к. он тоже военный
![image](https://user-images.githubusercontent.com/19251320/53692461-06823d00-3d99-11e9-97a5-1c67bce2f6cd.png)

2019-03-03 07:46 UTC, PROPHESSOR commented
Дословный перевод звучит плохо, лучше адаптировать как `я открыл дверь`
![image](https://user-images.githubusercontent.com/19251320/53692469-2a458300-3d99-11e9-92ee-d8a07b03ac1a.png)

2019-03-03 07:51 UTC, PROPHESSOR commented
**Эту** дверь заклинило
![image](https://user-images.githubusercontent.com/19251320/53692503-e0a96800-3d99-11e9-8b0f-8db503bd2ed7.png)

2019-03-03 07:53 UTC, PROPHESSOR commented
Лучше "скорее найди ключ"
![image](https://user-images.githubusercontent.com/19251320/53692517-34b44c80-3d9a-11e9-817a-74abd92adf91.png)

2019-03-03 07:58 UTC, PROPHESSOR commented
Слово `практически` влезает
![image](https://user-images.githubusercontent.com/19251320/53692563-e784aa80-3d9a-11e9-9f1c-6deb1c80a53f.png)

2019-03-03 08:00 UTC, PROPHESSOR commented
В восточной комнате один лишь Малрас
![image](https://user-images.githubusercontent.com/19251320/53692576-1ef35700-3d9b-11e9-8976-38ae2d2387cd.png)

2019-03-03 08:01 UTC, PROPHESSOR commented
[Почта]
![image](https://user-images.githubusercontent.com/19251320/53692585-3e8a7f80-3d9b-11e9-9d50-7831d6805bf9.png)

2019-03-03 08:04 UTC, PROPHESSOR commented
Вообще не похоже, просто достал
![image](https://user-images.githubusercontent.com/19251320/53692613-c96b7a00-3d9b-11e9-8252-e638d6f56e7d.png)

2019-03-03 08:16 UTC, PROPHESSOR commented
Исправил баги выше

2019-03-15 18:13 UTC, PROPHESSOR commented
@MorthimerMcMare ты там долго? Вон уже конфликты файлов появились!

2019-03-16 17:06 UTC, MorthimerMcMare requested changes
Заголовок "Про ее":
![](https://media.discordapp.net/attachments/505122055935623199/556483457375666176/unknown.png?width=798&height=426)

Нет запятой после "и" во второй строке.
![](https://media.discordapp.net/attachments/505122055935623199/556491673493045298/unknown.png?width=756&height=426)

Отсутствует точка и перенос строки перед "Увидимся":
![](https://media.discordapp.net/attachments/505122055935623199/556492629777448960/unknown.png?width=755&height=426)

Здесь нет точки в конце:
![](https://media.discordapp.net/attachments/505122055935623199/556493937876008995/unknown.png?width=798&height=426)

По переносам: "Пе-ре-клю-ча-ться" и "Жёл-тую".
![](https://media.discordapp.net/attachments/505122055935623199/556497139669270539/unknown.png?width=756&height=426)
![](https://media.discordapp.net/attachments/505122055935623199/556498046037524521/unknown.png?width=798&height=426)

Нет запятой:
![](https://media.discordapp.net/attachments/505122055935623199/556506701914963968/unknown.png?width=798&height=426)

Обращение к Би Джею должно выделяться запятыми, если здесь не особый, вульгарный стиль общения:
![](https://media.discordapp.net/attachments/505122055935623199/556506815853232139/unknown.png?width=798&height=426)

2019-03-22 23:03 UTC, PROPHESSOR commented
Исправлено.
Отправляю на повторный review.

2019-03-25 15:02 UTC, MorthimerMcMare requested changes
"Та-бель-но-е":
![](https://media.discordapp.net/attachments/332528078733705218/559734938610565120/unknown.png?width=798&height=426)

"Пе-ре-клю-ча-ться":
![](https://media.discordapp.net/attachments/332528078733705218/559746520065376257/unknown.png?width=798&height=426)

"М. Росс", указанный в заголовке письма, своей подписью не светится:
![](https://media.discordapp.net/attachments/332528078733705218/559748120490016770/unknown.png?width=798&height=426)

Опять ошибки с "ё"?
![](https://media.discordapp.net/attachments/332528078733705218/559751131396309033/unknown.png?width=756&height=426)

2019-03-25 16:30 UTC, PROPHESSOR commented
Исправил всё, кроме подписи Росса...
Я не знаю, как его зовут

2019-03-26 17:13 UTC, MorthimerMcMare approved these changes

2019-03-26 18:28 UTC, merged